apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y03as6ufs-nodejs 
  janus-idp.io/tekton: y03as6ufs-nodejs
  backstage.io/kubernetes-id: y03as6ufs-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y03as6ufs-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml