apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y03as6ufs-nodejs
  janus-idp.io/tekton: y03as6ufs-nodejs
  backstage.io/kubernetes-id: y03as6ufs-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y03as6ufs-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
